const Groq = require('groq-sdk');

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

class CodeProcessor {
    /**
     * Detect the programming language of the code
     */
    static async detectLanguage(code) {
        try {
            const prompt = `Identify the programming language of this code. Respond with ONLY the language name (e.g., C, C++, Java, Python, JavaScript).

Code:
${code}

Language:`;

            const completion = await groq.chat.completions.create({
                messages: [{ role: 'user', content: prompt }],
                model: 'llama-3.3-70b-versatile',
                temperature: 0.1,
                max_tokens: 50,
            });

            const language = completion.choices[0]?.message?.content?.trim() || 'Unknown';
            console.log('Detected language:', language);
            return language;
        } catch (error) {
            console.error('Language detection error:', error.message);
            return 'Unknown';
        }
    }

    /**
     * Clean and format code
     */
    static async cleanCode(code) {
        const lines = code.split('\n');
        const cleaned = lines
            .map(line => line.trimEnd())
            .filter(line => line.length > 0 || lines.indexOf(line) === 0)
            .join('\n');
        
        return cleaned.trim();
    }

    /**
     * Transform code from source to target language using Groq AI
     */
    static async transformCode(sourceCode, sourceLanguage, targetLanguage) {
        try {
            const prompt = `You are an expert programmer. Transform this ${sourceLanguage} code to clean, idiomatic ${targetLanguage} code.

IMPORTANT RULES:
1. Output ONLY the transformed ${targetLanguage} code
2. NO explanations, NO markdown, NO JSON formatting
3. NO comments except minimal inline comments where absolutely necessary
4. Use ${targetLanguage} best practices and idioms
5. Keep the code clean and concise
6. Preserve the exact logic and functionality

Source ${sourceLanguage} code:
${sourceCode}

Transformed ${targetLanguage} code:`;

            const completion = await groq.chat.completions.create({
                messages: [{ role: 'user', content: prompt }],
                model: 'llama-3.3-70b-versatile',
                temperature: 0.2,
                max_tokens: 2000,
            });

            let transformedCode = completion.choices[0]?.message?.content || '';
            
            // Clean up the response
            transformedCode = transformedCode
                .replace(/```[\w]*\n?/g, '') // Remove markdown code blocks
                .replace(/^Here'?s? the .*?:\n*/i, '') // Remove "Here's the code:" type lines
                .replace(/^The transformed .*?:\n*/i, '') // Remove explanation lines
                .trim();

            console.log('Transformation successful');

            // Generate a simple explanation
            const explanation = `Successfully transformed ${sourceLanguage} code to ${targetLanguage}. The converted code preserves the original logic while using ${targetLanguage} syntax and conventions.`;

            return {
                transformed_code: transformedCode,
                explanation: explanation,
                summary: `Converted from ${sourceLanguage} to ${targetLanguage}`,
                warnings: []
            };

        } catch (error) {
            console.error('Code transformation error:', error.message);
            throw new Error('Failed to transform code: ' + error.message);
        }
    }

    /**
     * Generate comparison report
     */
    static generateComparisonReport(originalCode, transformedCode, sourceLanguage, targetLanguage) {
        const report = `# Code Migration Report

## Source Language: ${sourceLanguage}
## Target Language: ${targetLanguage}

### Original Code:
\`\`\`${sourceLanguage.toLowerCase()}
${originalCode}
\`\`\`

### Transformed Code:
\`\`\`${targetLanguage.toLowerCase()}
${transformedCode}
\`\`\`

---
Generated by CoreShift - AI-Powered Code Migration
`;
        return report;
    }
}

module.exports = CodeProcessor;