const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } = require('docx');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class DownloadService {
    /**
     * Generate DOCX file from code transformation
     */
    async generateDOCX(originalCode, transformedCode, sourceLanguage, targetLanguage, projectName) {
        try {
            const doc = new Document({
                sections: [{
                    properties: {},
                    children: [
                        // Title
                        new Paragraph({
                            text: "Code Transformation Report",
                            heading: HeadingLevel.HEADING_1,
                            alignment: AlignmentType.CENTER,
                            spacing: { after: 400 }
                        }),

                        // Project Info
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: "Project: ",
                                    bold: true
                                }),
                                new TextRun(projectName || "Code Transformation")
                            ],
                            spacing: { after: 200 }
                        }),

                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: "Source Language: ",
                                    bold: true
                                }),
                                new TextRun(sourceLanguage)
                            ],
                            spacing: { after: 200 }
                        }),

                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: "Target Language: ",
                                    bold: true
                                }),
                                new TextRun(targetLanguage)
                            ],
                            spacing: { after: 400 }
                        }),

                        // Original Code Section
                        new Paragraph({
                            text: "Original Code",
                            heading: HeadingLevel.HEADING_2,
                            spacing: { before: 400, after: 200 }
                        }),

                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: originalCode,
                                    font: "Courier New",
                                    size: 20
                                })
                            ],
                            spacing: { after: 400 },
                            style: "code"
                        }),

                        // Transformed Code Section
                        new Paragraph({
                            text: "Transformed Code",
                            heading: HeadingLevel.HEADING_2,
                            spacing: { before: 400, after: 200 }
                        }),

                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: transformedCode,
                                    font: "Courier New",
                                    size: 20
                                })
                            ],
                            spacing: { after: 400 },
                            style: "code"
                        }),

                        // Footer
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: "\n\nGenerated by CoreShift - AI-Powered Code Migration Platform",
                                    italics: true,
                                    size: 18
                                })
                            ],
                            alignment: AlignmentType.CENTER,
                            spacing: { before: 600 }
                        })
                    ]
                }]
            });

            // Generate buffer
            const buffer = await Packer.toBuffer(doc);
            return buffer;

        } catch (error) {
            console.error('DOCX generation error:', error);
            throw new Error(`Failed to generate DOCX: ${error.message}`);
        }
    }

    /**
     * Generate PDF file from code transformation
     */
    async generatePDF(originalCode, transformedCode, sourceLanguage, targetLanguage, projectName) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const chunks = [];

                doc.on('data', chunk => chunks.push(chunk));
                doc.on('end', () => resolve(Buffer.concat(chunks)));
                doc.on('error', reject);

                // Title
                doc.fontSize(24)
                   .font('Helvetica-Bold')
                   .text('Code Transformation Report', { align: 'center' });
                
                doc.moveDown();

                // Project Info
                doc.fontSize(12)
                   .font('Helvetica-Bold')
                   .text('Project: ', { continued: true })
                   .font('Helvetica')
                   .text(projectName || 'Code Transformation');

                doc.font('Helvetica-Bold')
                   .text('Source Language: ', { continued: true })
                   .font('Helvetica')
                   .text(sourceLanguage);

                doc.font('Helvetica-Bold')
                   .text('Target Language: ', { continued: true })
                   .font('Helvetica')
                   .text(targetLanguage);

                doc.moveDown(2);

                // Original Code Section
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .text('Original Code');

                doc.moveDown();

                doc.fontSize(9)
                   .font('Courier')
                   .text(originalCode, {
                       lineGap: 2
                   });

                doc.moveDown(2);

                // Add new page if needed
                if (doc.y > 650) {
                    doc.addPage();
                }

                // Transformed Code Section
                doc.fontSize(16)
                   .font('Helvetica-Bold')
                   .text('Transformed Code');

                doc.moveDown();

                doc.fontSize(9)
                   .font('Courier')
                   .text(transformedCode, {
                       lineGap: 2
                   });

                // Footer
                doc.moveDown(3);
                doc.fontSize(10)
                   .font('Helvetica-Oblique')
                   .text('Generated by CoreShift - AI-Powered Code Migration Platform', {
                       align: 'center'
                   });

                doc.end();

            } catch (error) {
                console.error('PDF generation error:', error);
                reject(new Error(`Failed to generate PDF: ${error.message}`));
            }
        });
    }

    /**
     * Generate simple text file
     */
    generateTXT(originalCode, transformedCode, sourceLanguage, targetLanguage, projectName) {
        const content = `
CODE TRANSFORMATION REPORT
==========================

Project: ${projectName || 'Code Transformation'}
Source Language: ${sourceLanguage}
Target Language: ${targetLanguage}
Generated: ${new Date().toLocaleString()}

----------------------------------------
ORIGINAL CODE (${sourceLanguage})
----------------------------------------

${originalCode}

----------------------------------------
TRANSFORMED CODE (${targetLanguage})
----------------------------------------

${transformedCode}

========================================
Generated by CoreShift - AI-Powered Code Migration Platform
`;
        return Buffer.from(content, 'utf-8');
    }

    /**
     * Generate comparison report (markdown)
     */
    generateReport(originalCode, transformedCode, sourceLanguage, targetLanguage, projectName, explanation) {
        const content = `# Code Transformation Report

## Project Information
- **Project:** ${projectName || 'Code Transformation'}
- **Source Language:** ${sourceLanguage}
- **Target Language:** ${targetLanguage}
- **Date:** ${new Date().toLocaleString()}

---

## Original Code

\`\`\`${sourceLanguage.toLowerCase()}
${originalCode}
\`\`\`

---

## Transformed Code

\`\`\`${targetLanguage.toLowerCase()}
${transformedCode}
\`\`\`

---

## Transformation Details

${explanation || 'Code successfully transformed from ' + sourceLanguage + ' to ' + targetLanguage + '.'}

---

## Summary

Successfully transformed code from **${sourceLanguage}** to **${targetLanguage}**.

- Original lines: ${originalCode.split('\n').length}
- Transformed lines: ${transformedCode.split('\n').length}

---

*Generated by CoreShift - AI-Powered Code Migration Platform*
`;
        return Buffer.from(content, 'utf-8');
    }
}

module.exports = new DownloadService();