import React, { useState } from 'react';
import { Container, Row, Col, Card, Form, Button, Tabs, Tab, Navbar } from 'react-bootstrap';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { projectAPI } from '../../services/api';

function ProjectView() {
    const { id } = useParams();
    const navigate = useNavigate();
    
    // State
    const [code, setCode] = useState('');
    const [targetLanguage, setTargetLanguage] = useState('python');
    const [fileId, setFileId] = useState(null);
    const [detectedLanguage, setDetectedLanguage] = useState('');
    const [transformedCode, setTransformedCode] = useState('');
    const [explanation, setExplanation] = useState('');
    const [summary, setSummary] = useState('');
    const [loading, setLoading] = useState(false);
    const [step, setStep] = useState(1);

    const handleUpload = async () => {
        if (!code.trim()) {
            toast.error('Please enter some code');
            return;
        }

        setLoading(true);
        try {
            const response = await projectAPI.uploadCode(id, { code });
            setFileId(response.data.file_id);
            setDetectedLanguage(response.data.detected_language);
            toast.success(`Code uploaded! Detected: ${response.data.detected_language}`);
            setStep(2);
        } catch (error) {
            toast.error('Failed to upload code');
        } finally {
            setLoading(false);
        }
    };

    const handleMigrate = async () => {
        setLoading(true);
        try {
            const response = await projectAPI.migrate(id, {
                file_id: fileId,
                target_language: targetLanguage,
            });

            setTransformedCode(response.data.migration.transformed_code);
            setExplanation(response.data.explanation);
            setSummary(response.data.summary);
            toast.success('Migration completed successfully!');
            setStep(3);
        } catch (error) {
            toast.error(error.response?.data?.error || 'Migration failed');
        } finally {
            setLoading(false);
        }
    };

    const handleDownload = (content, filename) => {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleDownloadReport = () => {
        const report = `# CoreShift Migration Report

## Summary
${summary}

## Detected Language
${detectedLanguage}

## Target Language
${targetLanguage}

## Explanation
${explanation}

## Original Code
\`\`\`
${code}
\`\`\`

## Transformed Code
\`\`\`
${transformedCode}
\`\`\`

---
Generated by CoreShift - AI-Powered Code Migration
Student: Jinumol James, 3rd DC BCA, CMS College Kottayam
`;
        handleDownload(report, 'migration-report.md');
    };

    return (
       <div style={{ backgroundColor: '#87CEEB', minHeight: '100vh' }}>
            <Navbar bg="success" variant="dark" className="mb-4">
                <Container>
                    <Navbar.Brand style={{ fontSize: '1.5rem', fontWeight: 'bold' }}>
                        CoreShift - Code Migration
                    </Navbar.Brand>
                    <Button variant="light" size="sm" onClick={() => navigate('/dashboard')}>
                        ← Back to Dashboard
                    </Button>
                </Container>
            </Navbar>

            <Container className="py-4">
                {/* Step Indicator */}
                <div className="text-center mb-4">
                    <h4>
                        <span className={`badge ${step >= 1 ? 'bg-success' : 'bg-secondary'} me-2`}>1. Upload</span>
                        <span className={`badge ${step >= 2 ? 'bg-success' : 'bg-secondary'} me-2`}>2. Configure</span>
                        <span className={`badge ${step >= 3 ? 'bg-success' : 'bg-secondary'}`}>3. Results</span>
                    </h4>
                </div>

                {/* Step 1: Upload Code */}
                {step === 1 && (
                    <Card>
                        <Card.Header className="bg-success text-white">
                            <h4 className="mb-0">Step 1: Upload Your Code</h4>
                        </Card.Header>
                        <Card.Body>
                            <Form.Group className="mb-3">
                                <Form.Label><strong>Paste your legacy code here:</strong></Form.Label>
                                <Form.Control
                                    as="textarea"
                                    rows={20}
                                    value={code}
                                    onChange={(e) => setCode(e.target.value)}
                                    placeholder="Paste your C, C++, Java, or other code here..."
                                    style={{ fontFamily: 'Consolas, monospace', fontSize: '14px' }}
                                />
                                <Form.Text className="text-muted">
                                    Supports: C, C++, Java, JavaScript, and more
                                </Form.Text>
                            </Form.Group>
                            <Button 
                                variant="success" 
                                size="lg"
                                onClick={handleUpload} 
                                disabled={loading || !code.trim()}
                            >
                                {loading ? 'Analyzing...' : 'Upload & Detect Language →'}
                            </Button>
                        </Card.Body>
                    </Card>
                )}

                {/* Step 2: Select Target Language */}
                {step === 2 && (
                    <Card>
                        <Card.Header className="bg-success text-white">
                            <h4 className="mb-0">Step 2: Choose Target Language</h4>
                        </Card.Header>
                        <Card.Body>
                            <Row>
                                <Col md={6}>
                                    <h5>Detected Source Language:</h5>
                                    <h3><span className="badge bg-info">{detectedLanguage}</span></h3>
                                </Col>
                                <Col md={6}>
                                    <Form.Group>
                                        <Form.Label><strong>Select Target Language:</strong></Form.Label>
                                        <Form.Select
                                            size="lg"
                                            value={targetLanguage}
                                            onChange={(e) => setTargetLanguage(e.target.value)}
                                        >
                                            <option value="python">Python</option>
                                            <option value="java">Java</option>
                                            <option value="javascript">JavaScript</option>
                                            <option value="typescript">TypeScript</option>
                                            <option value="go">Go</option>
                                            <option value="rust">Rust</option>
                                            <option value="csharp">C#</option>
                                        </Form.Select>
                                    </Form.Group>
                                </Col>
                            </Row>
                            <hr />
                            <div className="d-flex gap-2">
                                <Button variant="secondary" onClick={() => setStep(1)}>
                                    ← Back
                                </Button>
                                <Button 
                                    variant="success" 
                                    size="lg"
                                    onClick={handleMigrate} 
                                    disabled={loading}
                                >
                                    {loading ? 'Migrating with AI... (this may take 30 seconds)' : '🚀 Start AI Migration →'}
                                </Button>
                            </div>
                        </Card.Body>
                    </Card>
                )}

                {/* Step 3: Results */}
                {step === 3 && (
                    <div>
                        <Card className="mb-3">
                            <Card.Header className="bg-success text-white d-flex justify-content-between align-items-center">
                                <h4 className="mb-0">✅ Migration Complete!</h4>
                                <div>
                                    <Button 
                                        variant="light" 
                                        size="sm" 
                                        className="me-2"
                                        onClick={() => handleDownload(transformedCode, `migrated_code.${targetLanguage}`)}
                                    >
                                        📥 Download Code
                                    </Button>
                                    <Button 
                                        variant="outline-light" 
                                        size="sm"
                                        onClick={handleDownloadReport}
                                    >
                                        📄 Download Report
                                    </Button>
                                </div>
                            </Card.Header>
                        </Card>

                        <Card>
                            <Card.Body>
                                <Tabs defaultActiveKey="comparison" className="mb-3">
                                    <Tab eventKey="comparison" title="Side-by-Side Comparison">
                                        <Row>
                                            <Col md={6}>
                                                <h5>Original Code ({detectedLanguage})</h5>
                                                <pre style={{ 
                                                    background: '#f5f5f5', 
                                                    padding: '15px', 
                                                    borderRadius: '5px',
                                                    maxHeight: '500px',
                                                    overflow: 'auto',
                                                    fontSize: '13px'
                                                }}>
                                                    <code>{code}</code>
                                                </pre>
                                            </Col>
                                            <Col md={6}>
                                                <h5>Transformed Code ({targetLanguage})</h5>
                                                <pre style={{ 
                                                    background: '#e8f5e9', 
                                                    padding: '15px', 
                                                    borderRadius: '5px',
                                                    maxHeight: '500px',
                                                    overflow: 'auto',
                                                    fontSize: '13px'
                                                }}>
                                                    <code>{transformedCode}</code>
                                                </pre>
                                            </Col>
                                        </Row>
                                    </Tab>
                                    
                                    <Tab eventKey="explanation" title="AI Explanation">
                                        <Card className="bg-light">
                                            <Card.Body>
                                                <h5>Summary</h5>
                                                <p className="lead">{summary}</p>
                                                <hr />
                                                <h5>Detailed Explanation</h5>
                                                <p style={{ whiteSpace: 'pre-wrap' }}>{explanation}</p>
                                            </Card.Body>
                                        </Card>
                                    </Tab>
                                    
                                    <Tab eventKey="transformed" title="Transformed Code Only">
                                        <pre style={{ 
                                            background: '#f5f5f5', 
                                            padding: '15px', 
                                            borderRadius: '5px',
                                            maxHeight: '600px',
                                            overflow: 'auto'
                                        }}>
                                            <code>{transformedCode}</code>
                                        </pre>
                                    </Tab>
                                </Tabs>

                                <div className="text-center mt-4">
                                    <Button 
                                        variant="primary" 
                                        onClick={() => {
                                            setStep(1);
                                            setCode('');
                                            setTransformedCode('');
                                            setFileId(null);
                                        }}
                                    >
                                        Start New Migration
                                    </Button>
                                </div>
                            </Card.Body>
                        </Card>
                    </div>
                )}
            </Container>
        </div>
    );
}

export default ProjectView;
